# MariaDB with Adminer
# Single Node
# Requires
# Net mariadb-public
# Secret mariadb-root-password
# Label on node mariadb == 1
# DOMAIN var and domain for adminer created
version: '3.8'

volumes:
  data:
secrets:
  - mariadb-root-password:
      external: true

networks:
  mariadb-public:
    external: true
services:
  mariadb:
    image: mariadb:10.5.8-focal
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mariadb-root-password
    deploy:
      placement:
        constraints:
          - node.labels.mariadb == 1
      resources:
        limits:
          cpus: '0.99'
          memory: 900M
        reservations:
          cpus: '0.25'
          memory: 300M
    volumes:
      - data:/var/lib/mysql
        #      - "./sda:/home"
    networks:
      - mariadb-public:
          external: true
      - traefik-public:
          external: true
  adminer:
    image: adminer:4.8.0-standalone
    deploy:
      placement:
        constraints:
          - node.labels.mariadb == 1
        labels:
          - traefik.enable=true
          - traefik.docker.network=traefik-public
          - traefik.constraint-label=traefik-public
          # http router
          - traefik.http.routers.adminer-http.rule=Host(`${DOMAIN}`)
          - traefik.http.routers.adminer-http.entrypoints=http
          - traefik.http.routers.adminer-http.middleware=https-redirect
          #https router
          - traefik.http.routers.adminer-https.rule=Host(`${DOMAIN}`)
          - traefik.http.routers.adminer-https.entrypoints=https
          - traefik.http.routers.adminer-https.tls=true
          - traefik.http.routers.adminer-https.tls.certresolver=le
    networks:
      - traefik-public
      - mariadb-public


