# MariaDB 
# Single Node
# Requires
# Net mariadb-public
# Secret mariadb-root-password
# Label on node mariadb == 1
version: '3.8'

volumes:
  data:

secrets:
  mariadb-root-password:
    external: true

networks:
  mariadb-public:
    external: true
  traefik-public:
    external: true
      
services:
  mariadb:
    image: mariadb:10.5.8-focal
    secrets:
      - mariadb-root-password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mariadb-root-password
    deploy:
      placement:
        constraints:
          - node.labels.mariadb == 1
      resources:
        limits:
          cpus: '0.99'
          memory: 900M
        reservations:
          cpus: '0.25'
          memory: 300M
    volumes:
      - data:/var/lib/mysql
        #      - "./sda:/home"
    ports:
      - ${PORT}:3306
    networks:
      - mariadb-public
      - traefik-public


