# MariaDB 
# Single Node

version: '3.8'

volumes:
  data:

secrets:
  mariadb-root-password:
    external: true
    name: ${MARIADB_ROOT_PASSWORD}

networks:
  public:
    external: true
    name: ${MARIADB_PUBLIC_NETWORK}
      
services:
  mariadb:
    image: ${MARIADB_IMAGE}
    secrets:
      - mariadb-root-password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mariadb-root-password
    deploy:
      placement:
        constraints:
          - node.labels.${NODE_LABEL} == 1
      resources:
        limits:
          cpus: ${MARIADB_CPU_LIMIT}
          memory: ${MARIADB_MEMORY_LIMIT}
        reservations:
          cpus: ${MARIADB_CPU_RESERVATION}
          memory: ${MARIADB_MEMORY_RESERVATION}
    volumes:
      - data:/var/lib/mysql
    ports:
      - ${MARIADB_PORT}:3306
    networks:
      - public

